### ISSUE TITLE
cant start it working

### ISSUE THREAD

**Issue by zoldaten** [shupengwang20180508/yolov9.infer#1]
i see when start:
```
line 20, in <module>
    model = cv2.dnn.readNetFromONNX('weights/gelan-c.onnx')
cv2.error: OpenCV(4.9.0) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\onnx\onnx_importer.cpp:1053: error: (-2:Unspecified error) in function 'cv::dnn::dnn4_v20231225::ONNXImporter::handleNode'
> Node [Split@ai.onnx]:(onnx_node!/model.22/Split) parse error: OpenCV(4.9.0) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\layers\slice_layer.cpp:243: error: (-215:Assertion failed) inputs.size() == 1 in function 'cv::dnn::SliceLayerImpl::getMemoryShapes'
```

**Comment by AICVer** [comment]
> i see when start:
> 
> ```
> line 20, in <module>
>     model = cv2.dnn.readNetFromONNX('weights/gelan-c.onnx')
> cv2.error: OpenCV(4.9.0) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\onnx\onnx_importer.cpp:1053: error: (-2:Unspecified error) in function 'cv::dnn::dnn4_v20231225::ONNXImporter::handleNode'
> > Node [Split@ai.onnx]:(onnx_node!/model.22/Split) parse error: OpenCV(4.9.0) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\layers\slice_layer.cpp:243: error: (-215:Assertion failed) inputs.size() == 1 in function 'cv::dnn::SliceLayerImpl::getMemoryShapes'
> ```

you can have try with my exported model, and you can found it by the following link
链接: https://pan.baidu.com/s/1uNDO60PlP3LlKshW1nqTPg?pwd=AIWA 提取码: AIWA
